`define MODULE_NAME FFT_Top_512
`define TARGET_DEVICE_GW2A_18C
`define FIXED
`define FFT512
`define POINTS 512
`define POINTS_LOG 9
`define LOW_RESOURCE
`define MODE_FORWARD
`define OUTPUT_NATURAL
`define SCALING_NONE
`define INPUT_DATA_WIDTH 12
`define INPUT_DATA_WIDTH_LOG 3
`define TWIDDLE_FACTOR_WIDTH 16
`define TWIDDLE_FACTOR_WIDTH_LOG 4
`define OUTPUT_DATA_WIDTH 16
`define OUTPUT_DATA_WIDTH_LOG 4
`define FRC_DW 4
`define REDUCTION_ROUNDING
`define DSP_BLOCK_BASED
`define EBR_MEMORY
`define TDF_EBR_MEMORY
