`define MODULE_NAME FFT_Top_new
`define FIXED
`define FFT1024
`define POINTS 1024
`define POINTS_LOG 10
`define TARGET_DEVICE_GW1A2A
`define MODE_FORWARD
`define OUTPUT_NATURAL
`define SCALING_NONE
`define INPUT_DATA_WIDTH 24
`define INPUT_DATA_WIDTH_LOG 4
`define TWIDDLE_FACTOR_WIDTH 16
`define TWIDDLE_FACTOR_WIDTH_LOG 4
`define OUTPUT_DATA_WIDTH 27
`define OUTPUT_DATA_WIDTH_LOG 4
`define FRC_DW 3
`define REDUCTION_ROUNDING
`define DSP_BLOCK_BASED
`define EBR_MEMORY
`define TDF_EBR_MEMORY
